import { LegalLayout } from '../components/LegalLayout';
import { CONTACT_EMAIL, PRODUCT_NAME } from '../lib/site';

export function Terms() {
  return (
    <LegalLayout
      current="/terms"
      title="Terms & Conditions"
      intro={`These terms govern your use of the ${PRODUCT_NAME} extension and this website. By downloading or using the extension, you agree to them.`}
    >
      <h2>1. What {PRODUCT_NAME} is</h2>
      <p>
        {PRODUCT_NAME} is a Chrome extension that assists interviewers by transcribing a Google
        Meet conversation and generating suggested questions, answer evaluations, and an end-of-
        interview report using AI. It is an <strong>assistant</strong>: it surfaces signal to help
        a human make a better decision. It does not make hiring decisions and is not a substitute
        for your own judgment.
      </p>

      <h2>2. Bring your own keys</h2>
      <p>
        The extension processes interviews client-side and calls AI providers directly with your
        keys; we don’t host a backend that handles your interview content. To use it you must
        supply your own API keys for a transcription provider (Deepgram) and an LLM provider
        (Anthropic, OpenAI, Google, or xAI). You are responsible for:
      </p>
      <ul>
        <li>Obtaining and securing those keys;</li>
        <li>All usage fees and charges those providers bill to your accounts;</li>
        <li>Complying with each provider’s terms of service and acceptable-use policies.</li>
      </ul>
      <p>
        The limited data we do collect — the contact details you submit to download, and opt-in
        anonymous usage analytics — is described in our <a href="/privacy">Privacy Policy</a>, which
        forms part of these terms.
      </p>

      <h2>3. Acceptable use &amp; consent</h2>
      <p>
        You agree to use {PRODUCT_NAME} lawfully and ethically. In particular, you are solely
        responsible for:
      </p>
      <ul>
        <li>
          <strong>Recording and transcription consent.</strong> Many jurisdictions require that you
          inform participants — including the candidate — that the conversation is being
          transcribed or processed by AI, and in some cases obtain their consent. You must comply
          with all applicable laws where you and the candidate are located.
        </li>
        <li>
          <strong>Fair, non-discriminatory hiring.</strong> You remain responsible for ensuring
          your interview and hiring practices comply with employment and anti-discrimination law.
          AI output may be incomplete or wrong and must not be used as the sole basis for a
          decision.
        </li>
        <li>Not using the tool to harass, deceive, or harm any person.</li>
      </ul>

      <h2>4. AI output disclaimer</h2>
      <p>
        Ratings, suggested questions, and reports are generated by third-party AI models and may
        contain errors, omissions, or bias. They are provided <strong>“as is”</strong> for
        guidance only. You must independently verify anything you rely on. {PRODUCT_NAME} makes no
        warranty as to the accuracy, completeness, or fitness of any AI-generated output.
      </p>

      <h2>5. Prototype status</h2>
      <p>
        {PRODUCT_NAME} is an early prototype distributed as an unpacked Chrome extension. It may
        change, break, or be discontinued at any time, and is provided without any service-level
        commitment, uptime guarantee, or support obligation.
      </p>

      <h2>6. Intellectual property</h2>
      <p>
        The {PRODUCT_NAME} name, the extension, and this website are owned by us. You are granted a
        limited, revocable, non-exclusive license to install and use the extension for your own
        interviewing. You retain all rights to your own content (job descriptions, résumés,
        transcripts, and reports); we claim no ownership over it and never receive it.
      </p>

      <h2>7. Disclaimer of warranties</h2>
      <p>
        The software and website are provided <strong>“as is” and “as available,”</strong> without
        warranties of any kind, whether express or implied, including merchantability, fitness for
        a particular purpose, and non-infringement.
      </p>

      <h2>8. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, we will not be liable for any indirect, incidental,
        special, consequential, or punitive damages, or for any loss of data, hiring outcomes,
        profits, or third-party API costs, arising out of or related to your use of {PRODUCT_NAME}.
      </p>

      <h2>9. Changes to these terms</h2>
      <p>
        We may update these terms as the product evolves. Continued use after an update constitutes
        acceptance of the revised terms.
      </p>

      <h2>10. Contact</h2>
      <p>
        Questions about these terms? Reach us at{' '}
        <a href={`mailto:${CONTACT_EMAIL}`}>{CONTACT_EMAIL}</a>.
      </p>
    </LegalLayout>
  );
}
